# Site configuration
title: Kitchen Canvas
description: A culinary notebook with practical recipe tools.
baseurl: ""
url: "https://bubbamurphy.com"

# Build settings
markdown: kramdown
theme: null

collections:
  recipes:
    output: true
    permalink: /recipes/:path/

exclude:
 - Gemfile
 - Gemfile.lock
